
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: logging-demo
  labels:
    name: logging-demo
    k8s-app: k8s-app-logging-demo
spec:
  selector:
    matchLabels:
      name: demo-log-generator
      k8s-app: demo-log-generator
  template:
    metadata:
      labels:
        name: demo-log-generator
        k8s-app: demo-log-generator
      annotations:
        fluentd/multiline: "true"
    spec:
      containers:
      - name: busybox
        image: busybox
        command:
          - /bin/sh
          - -c
          - while sleep 5; do echo -e "$(date +'%Y-%m-%d %H:%M:%S%z') -- still logging...\nthis is the second line\nand the third line"; done