apiVersion: v1
kind: Pod
metadata:
  name: kibana
  labels:
    app.kubernetes.io/name: kibana 
spec:
#  hostAliases:
#  - ip: "10.103.254.157"
#    hostnames:
#    - "elasticsearch"
  containers:
  - env:
    - name: ELASTICSEARCH_URL
      value: http://elasticsearch:9200             
#    image: docker.io/bitnami/kibana:8.5.3
    image: docker.io/bitnami/kibana:8.6.2
    name: kibana
    ports:
    - containerPort: 5601


---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  labels:
    app.kubernetes.io/name: kibana    
spec:
  ports:
   - name: http
     protocol: TCP
     port: 5601
     targetPort: 5601
  selector:
    app.kubernetes.io/name: kibana    

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kibana
spec:
  tls:
  - hosts:
    - shop.neva.cloudns.nz
    secretName: prod-ext-tls
  rules:
  - http:
      paths:
      - path: /   
        pathType: Prefix
        backend:
          service:
            name: kibana
            port:
              number: 5601
            