---
apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  labels:
    k8s-app: logstash
data:
  logstash.yml: |-
    http.host: 0.0.0.0
    node.name: logstash
    pipeline.workers: 1
    pipeline.batch.size: 1

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-pipeline
  labels:
    k8s-app: logstash
data:
  service_stamped_json_logs.conf: |-
    input {
      beats {
        port => 5044
        codec => json {
          target => "[document]"
        }
      }  
    }
    output {
      stdout {}
      elasticsearch {
        hosts => "${ELASTICSEARCH_HOST:elasticsearch}:${ELASTICSEARCH_PORT:9200}"
        index => "dotnetlogs"
      }
    }  

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: logstash
  name: logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: logstash
  template:
    metadata:
      labels:
        k8s-app: logstash
    spec:
      volumes:
      - name: volumelogs
        hostPath:
          path: /mnt/logs
      - name: config
        configMap:
          defaultMode: 0600
          name: logstash-config
      - name: pipeline
        configMap:
          defaultMode: 0600
          name: logstash-pipeline
      containers:
      - env:
        - name: LS_JAVA_OPTS
          value: -Xms512m -Xmx512m
        - name: ELASTICSEARCH_HOST
          value: elasticsearch.efk.svc.cluster.local
        - name: ELASTICSEARCH_PORT
          value: "9200"
#        - name: ELASTICSEARCH_USERNAME
#          value: elastic
#        - name: ELASTICSEARCH_PASSWORD
#          value: changeme
        - name: ELASTIC_CLOUD_ID
          value:
        - name: ELASTIC_CLOUD_AUTH
          value:
        securityContext:
          runAsUser: 0
        args: 
          - -f
          - /usr/share/logstash/config/pipelines/service_stamped_json_logs.conf
        image: elastic/logstash:8.6.2
        imagePullPolicy: Always
        name: logstash
        ports:
        - containerPort: 5044
        volumeMounts:
          - name: volumelogs  
            mountPath: /logs 
          - name: config
            mountPath: /usr/share/logstash/config/logstash.yml
            readOnly: true
            subPath: logstash.yml
          - name: pipeline
            mountPath: /usr/share/logstash/config/pipelines/service_stamped_json_logs.conf
            readOnly: true

---
apiVersion: v1
kind: Service
metadata:
  name: logstash
  labels:
    k8s-app: logstash
spec:
  selector:
    k8s-app: logstash
  ports:
  - name: logstash
    port: 5044
    targetPort: 5044
    protocol: TCP