version: '3.8'

services:
  postgresdb:
    build:
      context: ./postgresdb
    healthcheck:
      test: test -f /tmp/finished.ok
      interval: 5s
      timeout: 10s
      retries: 120
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${PASSWORD_DB:-postgres}
      - DB_NAME_API=keycloak
    ports:
      - '54321:5432'
    volumes:
      - ${NS_LOG_PATH:-./logs}/postgres:/logs
      - postgres-data:/var/lib/postgresql

  mailhog:
    image: mailhog/mailhog
    restart: always
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

  traefik:
    image: traefik:v1.7
    command: --api --docker
    restart: always
    ports:
      - "8081:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  postgres-data:

